on:
  push:
    branches:
    - main

permissions:
  id-token: write
  contents: read

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set Node.js version
      run: echo "NODE_VERSION=18.x" >> $GITHUB_ENV

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Check Node.js version
      run: node -v

    - name: Install ADF Utilities package
      run: npm install
      working-directory: ${{github.workspace}}/ADFroot/build

    - name: Validate
      run: npm run build validate ${{github.workspace}}/ADFroot/ /subscriptions/b5c2fa53-cf8f-4f5c-b744-ab40d3967c24/resourceGroups/rg_ci_cd_new_dev/providers/Microsoft.DataFactory/factories/df-new-dev
      working-directory: ${{github.workspace}}/ADFroot/build

    - name: Validate and Generate ARM template
      run: npm run build export ${{github.workspace}}/ADFroot/ /subscriptions/b5c2fa53-cf8f-4f5c-b744-ab40d3967c24/resourceGroups/rg_ci_cd_new_dev/providers/Microsoft.DataFactory/factories/df-new-dev "ExportedArmTemplate"
      working-directory: ${{github.workspace}}/ADFroot/build

    - name: Create Custom ARM Parameters File for DEV
      run: |
        mkdir -p ${{github.workspace}}/ADFroot/build
        echo '{
          "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
          "contentVersion": "1.0.0.0",
          "parameters": {
            "factoryName": {"value": "df-new-dev"},
            "ls_db_dev_properties_typeProperties_connectionString_secretName": {"value": "secret-db-dev"},
            "ls_kv_dev_properties_typeProperties_baseUrl": {"value": "https://kv-l-dev.vault.azure.net/"},
            "ls_storage_dev_properties_typeProperties_url": {"value": "https://storageldev.dfs.core.windows.net"},
            "ls_storage_dev_properties_typeProperties_accountKey_secretName": {"value": "secret-storage-dev"}
          }
        }' > ${{github.workspace}}/ADFroot/build/ARMTemplateParametersForFactory.json

    - name: Upload ARM Template and Parameters
      uses: actions/upload-artifact@v3
      with:
        name: ADF-Artifacts
        path: |
          ${{github.workspace}}/ADFroot/build/ExportedArmTemplate/ARMTemplateForFactory.json
          ${{github.workspace}}/ADFroot/build/ARMTemplateParametersForFactory.json

  deploy-uat:
    needs: build-dev
    runs-on: ubuntu-latest
    steps:
    - name: Download ADF Artifacts
      uses: actions/download-artifact@v3.0.2
      with:
        name: ADF-Artifacts

    - name: Create Custom ARM Parameters File for UAT
      run: |
        mkdir -p ${{github.workspace}}/ADFroot/build
        echo '{
          "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
          "contentVersion": "1.0.0.0",
          "parameters": {
            "factoryName": {"value": "df-new-uat"},
            "ls_db_dev_properties_typeProperties_connectionString_secretName": {"value": "secret-db-uat"},
            "ls_kv_dev_properties_typeProperties_baseUrl": {"value": "https://kv-l-uat.vault.azure.net/"},
            "ls_storage_dev_properties_typeProperties_url": {"value": "https://storageluat.dfs.core.windows.net"},
            "ls_storage_dev_properties_typeProperties_accountKey_secretName": {"value": "secret-storage-uat"}
          }
        }' > ${{github.workspace}}/ADFroot/build/ARMTemplateParametersForFactory.json

    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: '${{ secrets.CONNECT_TO_UAT }}'
        enable-AzPSSession: true

    - name: Data-factory-deploy
      uses: Azure/data-factory-deploy-action@v1.2.0
      with:
        resourceGroupName: rg_ci_cd_new_uat
        dataFactoryName: df-new-uat
        armTemplateFile: ${{github.workspace}}/ADFroot/build/ExportedArmTemplate/ARMTemplateForFactory.json
        armTemplateParametersFile: ${{github.workspace}}/ADFroot/build/ARMTemplateParametersForFactory.json
