on:
  push:
    branches:
    - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set Node.js version
      run: echo "NODE_VERSION=18.x" >> $GITHUB_ENV

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Check Node.js version
      run: node -v

    - name: Install ADF Utilities package
      run: npm install
      working-directory: ${{github.workspace}}/ADFroot/build

    - name: Validate and Generate ARM template
      run: npm run build export ${{github.workspace}}/ADFroot/ /subscriptions/b5c2fa53-cf8f-4f5c-b744-ab40d3967c24/resourceGroups/rg_ci_cd_new_dev/providers/Microsoft.DataFactory/factories/df-new-dev "ExportedArmTemplate"
      working-directory: ${{github.workspace}}/ADFroot/build

    - name: Update ARM Template to Include New Parameter
      run: |
        jq '.parameters |= . + {"ls_AzureStorage_properties_typeProperties_accountKey_secretName": {"defaultValue": "secret-storage-dev", "type": "string"}}' ARMTemplateForFactory.json > tempTemplate.json
        mv tempTemplate.json ARMTemplateForFactory.json
      working-directory: ${{github.workspace}}/ADFroot/build/ExportedArmTemplate

    - name: Update ARM Parameters File for UAT
      run: |
        jq '.parameters |= . + {"ls_AzureStorage_properties_typeProperties_accountKey_secretName": {"value": "secret-storage-uat"}}' ARMTemplateParametersForFactory.json > tempParameters.json
        mv tempParameters.json ARMTemplateParametersForFactory.json
      working-directory: ${{github.workspace}}/ADFroot/build/ExportedArmTemplate

    - name: Upload ARM Template and Parameters
      uses: actions/upload-artifact@v3
      with:
        name: ADF-Artifacts
        path: |
          ${{github.workspace}}/ADFroot/build/ExportedArmTemplate/ARMTemplateForFactory.json
          ${{github.workspace}}/ADFroot/build/ExportedArmTemplate/ARMTemplateParametersForFactory.json

    - name: Download ADF Artifacts
      uses: actions/download-artifact@v3.0.2
      with:
        name: ADF-Artifacts

    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: '${{ secrets.CONNECT_TO_UAT }}'
        enable-AzPSSession: true

    - name: Deploy ARM Template to UAT
      uses: Azure/data-factory-deploy-action@v1.2.0
      with:
        resourceGroupName: rg_ci_cd_new_uat
        dataFactoryName: df-new-uat
        armTemplateFile: ARMTemplateForFactory.json
        armTemplateParametersFile: ARMTemplateParametersForFactory.json
        additionalParameters: factoryName=df-new-uat ls_db_dev_properties_typeProperties_connectionString_secretName=secret-db-uat ls_kv_dev_properties_typeProperties_baseUrl=https://kv-l-uat.vault.azure.net/ ls_storage_dev_properties_typeProperties_url=https://storageluat.dfs.core.windows.net
