on:
  push:
    branches:
    - main

permissions:
  id-token: write
  contents: read

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set Node.js version
      run: echo "NODE_VERSION=18.x" >> $GITHUB_ENV

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Check Node.js version
      run: node -v      

    - name: install ADF Utilities package
      run: npm install
      working-directory: ${{github.workspace}}/ADFroot/build

    - name: Validate
      run: npm run build validate ${{github.workspace}}/ADFroot/ /subscriptions/b5c2fa53-cf8f-4f5c-b744-ab40d3967c24/resourceGroups/rg_ci_cd_new_dev/providers/Microsoft.DataFactory/factories/df-new-dev
      working-directory: ${{github.workspace}}/ADFroot/build

    - name: Validate and Generate ARM template
      run: npm run build export ${{github.workspace}}/ADFroot/ /subscriptions/b5c2fa53-cf8f-4f5c-b744-ab40d3967c24/resourceGroups/rg_ci_cd_new_dev/providers/Microsoft.DataFactory/factories/df-new-dev "ExportedArmTemplate"
      working-directory: ${{github.workspace}}/ADFroot/build

    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ExportedArmTemplate
        path: ${{github.workspace}}/ADFroot/build/ExportedArmTemplate

  deploy-uat:
    needs: build-dev
    runs-on: ubuntu-latest
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.2
      with:
        name: ExportedArmTemplate

    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: '${{ secrets.CONNECT_TO_UAT }}'
        enable-AzPSSession: true

    - name: data-factory-deploy
      uses: Azure/data-factory-deploy-action@v1.2.0
      with:
        resourceGroupName: rg_ci_cd_new_uat
        dataFactoryName: df-new-uat
        armTemplateFile: ARMTemplateForFactory.json
        armTemplateParametersFile: ARMTemplateParametersForFactory.json
        additionalParameters: factoryName=df-new-uat ls_db_dev_properties_typeProperties_connectionString_secretName=secret-db-uat ls_kv_dev_properties_typeProperties_baseUrl=https://kv-l-uat.vault.azure.net/ ls_sas_storage_dev_properties_typeProperties_sasUri_secretName=secret-sas-storage-uat


  deactivate-dev-triggers:
    needs: deploy-uat
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
  
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.CONNECT_TO_DEV }}
  
   



    - name: Deactivate All Triggers in DEV ADF
      run: |
        RESOURCE_GROUP="rg_ci_cd_new_dev"
        DATA_FACTORY_NAME="df-new-dev"
  
        # Get all triggers in the data factory
        triggers=$(az datafactory trigger list --resource-group $RESOURCE_GROUP --factory-name $DATA_FACTORY_NAME --query "[].name" -o tsv)
        echo "Triggers found: $triggers"
  
        # Deactivate each trigger
        for trigger in $triggers
        do
          echo "Attempting to pause trigger: $trigger"
          stop_output=$(az datafactory trigger stop --resource-group $RESOURCE_GROUP --factory-name $DATA_FACTORY_NAME --name $trigger 2>&1)
          echo "Output of stop command for $trigger: $stop_output"
        done
  
